### ISSUE TITLE
Broken nd_reload_fix

### ISSUE THREAD

**Issue by stickz** [stickz/Redstone#14]
There is a glitch with nuclear dawn causing double reloading. The nd_reload_fix plugin attemps to resolve that issue, but it accidentally messes up client aiming. Can this be fixed?

**Comment by stickz** [comment]
@yedpodtrzitko

**Comment by yedpodtrzitko** [comment]
Show me your advanced coding abilities and fix it yourself.

**Comment by stickz** [comment]
Just thought I'd redirect you to this issue report. It's up to you, what gets done this knowledge.

I don't have time to look into and fix this issue. It's sitting on git-hub not used currently.
