### ISSUE TITLE
Map vote dialog looks messy

### ISSUE THREAD

**Issue by sergeylukin** [stickz/Redstone#247]
Here is how map vote dialog looks like on my screen (OS X, experimental branch of ND):

<img width="1680" alt="screen shot 2016-11-26 at 1 33 20 am" src="https://cloud.githubusercontent.com/assets/720339/20640765/baf29c56-b3f0-11e6-9e38-3f462d3de059.png">

I think it's also related to similar behavior of chat message input where characters overlap one on another sometimes

**Comment by stickz** [comment]
This looks like a problem on the lower level than the mapchooser server plugin.

Is there a reason why you're running the experimental branch? Windows doesn't even have one anymore.

**Comment by sergeylukin** [comment]
I didn't know experimental was merged. Will try the stable tonight.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: stickzSent: Saturday, November 26, 2016 17:29To: stickz/RedstoneReply To: stickz/RedstoneCc: Sergey Lukin; AuthorSubject: Re: [stickz/Redstone] Map vote dialog looks messy (#247)This looks like a problem on the lower level than the mapchooser server plugin.
Is there a reason why you're running the experimental branch? Windows doesn't even have one anymore.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stickz/Redstone","title":"stickz/Redstone","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stickz/Redstone"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stickz in #247: This looks like a problem on the lower level than the mapchooser server plugin.\r\n\r\nIs there a reason why you're running the experimental branch? Windows doesn't even have one anymore."}],"action":{"name":"View Issue","url":"https://github.com/stickz/Redstone/issues/247#issuecomment-263069290"}}}

**Comment by sergeylukin** [comment]
I've just noticed that I'm not using the experimental branch. It's not available on OS X as well.
So where should I report this issue?

**Comment by stickz** [comment]
I'm going to make a change to the mapchooser plugin in a couple days. There's a function to trim the string that can be used before displaying the information in a panel. This diagnostic measure should be tested first because there's a small chance it could at least cover up this problem, so it stops. I ran into an issue awhile ago when doing text file handling, where a string had tons of spaces on the end of it.

**Comment by sergeylukin** [comment]
Got it. Thanks for expanded explanation. Will play with sourcemod locally anytime soon and report in my findings. Let's keep this issue open for the meanwhile.
