### ISSUE TITLE
Accumulating Server Translations

### ISSUE THREAD

**Issue by stickz** [stickz/Redstone#363]
The following phrases could potentially be accumulated into `nd_common.phrases.txt`:
`Empire`
`Consort`
`Round Start Usage:` "This feature requires the match to be started"
`Round End Usage: `"This feature can't be used when the game is over"
`Feature Unavailable:` "This feature is currently unavailable"
`Already Voted:` "You've already voted for this feature."

**Comment by stickz** [comment]
@Chaosmeister Do you have any other suggestions for phrase accumulation?

**Comment by Chaosmeister** [comment]
`Waiting` is used twice, but as far as I can see, that's about it.

**Comment by stickz** [comment]
[This](https://github.com/stickz/Redstone/blob/master/addons/sourcemod/scripting/nd_teamdiff/commands.sp#L19) needs phrased and may be repeated in the feature. `Waiting` should be removed from nd_team_balancer.phrases. The warmup is separated and is no longer apart of that plugin.

**Comment by Chaosmeister** [comment]
`Feature Unavailable` is not used as a generalized phrase yet.  
it could be modified to:  
"This feature is currently unavailable: {cause}"

In another PR.
