### ISSUE TITLE
CI server always passes

### ISSUE THREAD

**Issue by sergeylukin** [stickz/Redstone#44]
There is a bug in current CI build system. This build should be marked as failed, but was marked as "passed" instead: https://travis-ci.org/stickz/Redstone/jobs/114107059

Regardless, this commit should be reverted in my opinion: https://github.com/stickz/Redstone/commit/59037d0100b6962cd7ae231dd73e2a0f553ba428 and retried after this issue is resolved

**Comment by stickz** [comment]
This issue is resolved and a commit has been merged to fix that error.
