### ISSUE TITLE
Server auto reboot

### ISSUE THREAD

**Issue by sergeylukin** [stickz/Redstone#62]
Regarding the auto reboot script you're looking for. @stickz did you see this plugin: https://forums.alliedmods.net/showthread.php?p=777168

**Comment by stickz** [comment]
Yup, I've seen that plugin and actually tried it before. The _restart command doesn't work on Nuclear Dawn for some reason. It could be the way it's run on screens; but, I doubt it.

**Comment by sergeylukin** [comment]
According to what I've seen in [startup_scripts](https://github.com/stickz/Redstone/tree/master/startup_scripts) `screen` has [srcds_run](https://github.com/stickz/Redstone/blob/master/startup_scripts/srcds_run) process running even when server process is shut down so it shouldn't be related to that.

All you have to find is a way to shutdown server via plugin, it will be auto-restarted by `srcds_run` then. Also you have better control inside plugin as you can restart when there are no players. While if I will come up with OS-level task it'd brutally force server shutdown even if players are in the middle of playing which just doesn't feel right.

According to Valve's reference: https://developer.valvesoftware.com/wiki/Console_Command_List command is `restart` and not `_restart`. May that be it?

**Comment by stickz** [comment]
The restart commands do not work on Nuclear Dawn. An auto-restart script would likely need to be defined as a Linux OS task. There's always a downtime anyways where nobody is playing.

**Comment by sergeylukin** [comment]
NP let me see what I can come up with then

**Comment by stickz** [comment]
Is it possible to get the operating system time and define a constant for setting a daily restart?

**Comment by sergeylukin** [comment]
Sure, crontab allows exactly that
