### ISSUE TITLE
Missing Russian Translations #2

### ISSUE THREAD

**Issue by stickz** [stickz/Redstone#65]
#The following Russian translation phrase is  #missing.
[nd_tools](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_tools.phrases.txt)
[nd_commander_restrictions](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_commander_restrictions.phrases.txt)
[nd_player_interps](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_player_interps.phrases.txt)
[votemute_p](https://github.com/stickz/Redstone/blob/master/updater/votemute_p/translations/ru/votemute_p.phrases.txt)

**Comment by sergeylukin** [comment]
Please explain "Cookie Solution Assist" in [nd_tools](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_tools.phrases.txt)

**Comment by stickz** [comment]
"Solution Assist" is a feature which removes your chat messages in replaces them with a solution. For instance if you type "can't spawn", it say something like "change class and select anther spawn point"; or, if you type "kill, die, suicide etc" into chat without a trigger it will kill you.

The keyword "cookie" means in the !settings menu to toggle the feature on/off.

**Comment by stickz** [comment]
I just added the remaining phrases and added one the last missing Russian ones!

**Comment by sergeylukin** [comment]
In [Skill Required](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/ru/nd_commander_restrictions.phrases.txt#L78), what is the possible variable value?

In [votemute](https://github.com/stickz/Redstone/blob/master/updater/votemute_p/translations/ru/votemute_p.phrases.txt), what is the difference between Muted, Gagged and Silenced?

**Comment by stickz** [comment]
Skill Required: 5000-15000 currently here. http://rank.xenogamers.com/players/nd

Gag prevents the client from using server chat.
Mute prevents the client from using their microphone.
Silence is a communication block. (radio messages & gag + mute) plus other isolative restrictions.
