### ISSUE TITLE
Travis-Builder Issues

### ISSUE THREAD

**Issue by stickz** [stickz/Redstone#71]
@sergeylukin The server is currently in an infinite loop of updating plugins. The default version is being compiled and sent out; instead, of adjusting it to the new version. http://pastebin.com/T8awEbPt

Also, the builds are always passing even if the plugins have an errors.
https://travis-ci.org/stickz/Redstone/jobs/114954985

**Comment by sergeylukin** [comment]
I'm on it.

**Comment by sergeylukin** [comment]
Is it working as expected after #73 was merged?

**Comment by stickz** [comment]
Yup, it's working good. Plugins are failing properly now and the updater loop is fixed.

**Comment by sergeylukin** [comment]
Great!
