### ISSUE TITLE
Missing German Translations

### ISSUE THREAD

**Issue by stickz** [stickz/Redstone#82]
A lot of German translations are missing from servers. I have completed all the preparation necessary to easily translate the phrases without any extra work. Posted bellow is a full list of missing translations.

**Notice: structminigame and nd_universal_translator are the most important.**

[nd_continents](https://github.com/stickz/Redstone/blob/master/updater/nd_continents/translations/de/nd_continents.phrases.txt)
[nd_map_management](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/nd_map_management.phrases.txt)
[nd_universal_translator](https://github.com/stickz/Redstone/blob/master/updater/nd_universal_translator/translations/de/nd_universal_translator.phrases.txt)
[nd_radio_controls](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/nd_radio_controls.phrases.txt)
[nd_rockthevote](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/nd_rockthevote.phrases.txt)
[nd_surrender](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/nd_surrender.phrases.txt)
[nd_timelimit](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/nd_timelimit.phrases.txt)
[nd_tools](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/nd_tools.phrases.txt)
[nd_warmup](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/nd_warmup.phrases.txt)
[numbers](https://github.com/stickz/Redstone/blob/master/updater/nd_translation_updater/translations/de/numbers.phrases.txt)
[structminigame](https://github.com/stickz/Redstone/blob/master/updater/structminigame/translations/de/structminigame.phrases.txt)
[votemute_p](https://github.com/stickz/Redstone/blob/master/updater/votemute_p/translations/de/votemute_p.phrases.txt)

**Comment by Frank-Siebert** [comment]
Any preference for the translation?
Currently texts are often "vertex: Is requesting {1} research.". I would write "vertex: please research {1}." or rather the German equivalent.

**Comment by stickz** [comment]
You can change the words or order of the variables, so it makes more sense in German. Do what you think is best, for the person to understand the phrase. The biggest goal is to communicate a concept.

The phrase `vertex: Is requesting {1} research` is designed specially for the English language.
